### ISSUE TITLE
Problem with threads on Ruby 1.9.1

### ISSUE THREAD

**Issue by thomasaw** [kr/beanstalk-client-ruby#1]
I'm running into a problem that occurs when using beanstalk-client in combination with threads on Ruby 1.9.1. It doesn't occur with Ruby 1.8.7. The script below has the problem, but the problem doesn't occur every time the script runs. It seems to occur about 50% of the time. It occurs with beanstalkd 1.3 and 1.4.4.

The problem is that the script gets stuck and never hits the "End join" line.
# 

require 'rubygems'
require 'beanstalk-client'

$beanstalk = Beanstalk::Pool.new(['localhost:11300'])
$thread_num = 100

def enque(n)
  #puts "before enque " + n.to_s
  $beanstalk.put('hello world' + n.to_s)
  #puts "after enque " + n.to_s
end

threads = []

for i in 1 .. $thread_num
  threads << Thread::start {enque i}
end

puts "Start join"

for i in 1 .. $thread_num
  threads[i-1].join
end

puts "End join"

**Comment by kr** [comment]
The beanstalk client library does no internal synchronization. Programs that use it are expected to synchronize themselves. I'll add a note in the documentation saying this explicitly.

Since this program makes unsynchronized calls to the same connection in multiple threads, you shouldn't necessarily expect it to work in any version of ruby.
